services:
  yocto-dev:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: yocto-dev-container
    volumes:
      - ..:/home/yocto/yocto-obits-dunfell
      - ~/.ssh:/home/yocto/.ssh:ro
    ports:
      - "8080:8000"
    tty: true
    stdin_open: true
